// pythonframework handson/Frontend Development/Module2_FrontendDev/vinoth/handson_05/student-portal-react/src/components/CourseCard.jsx
import React from 'react';

export default function CourseCard({ id, name, code, credits, grade, onEnroll }) {
  return (
    <article className="course-card">
      <h3>{code} - {name}</h3>
      <p>Grade: {grade}</p>
      <span>Credits: {credits}</span>
      <br />
      <button 
        type="button" 
        onClick={() => onEnroll({ id, name, code, credits, grade })}
        className="enroll-btn"
      >
        Enroll
      </button>
    </article>
  );
}

// pythonframework handson/Frontend Development/Module2_FrontendDev/vinoth/handson_07/student-portal-angular/src/app/course-card/course-card.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  standalone: true,
  imports: [],
  templateUrl: './course-card.html',
  styleUrl: './course-card.css'
})
export class CourseCardComponent {
  @Input() name: string = '';
  @Input() code: string = '';
  @Input() credits: number = 0;
  @Input() grade: string = '';
}
