// pythonframework handson/Frontend Development/Module2_FrontendDev/vinoth/handson_06/student-portal-react/src/components/Header.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';

export default function Header() {
  const enrolledCourses = useSelector((state) => state.enrollment.enrolledCourses);

  return (
    <header className="header">
      <h1>Student Portal</h1>
      <nav>
        <Link to="/">Home</Link>
        <Link to="/courses">Courses</Link>
        <Link to="/profile">Profile ({enrolledCourses.length})</Link>
      </nav>
    </header>
  );
}

// pythonframework handson/Frontend Development/Module2_FrontendDev/vinoth/handson_08/student-portal-vue/src/components/Header.vue
<script setup>
import { RouterLink } from 'vue-router';
import { useEnrollmentStore } from '../stores/enrollment';

const enrollmentStore = useEnrollmentStore();
</script>

<template>
  <header class="header">
    <h1>Student Portal</h1>
    <nav>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">Profile ({{ enrollmentStore.enrolledCourses.length }})</RouterLink>
    </nav>
  </header>
</template>

<style scoped>
.header {
  background-color: #1e293b;
  color: white;
  padding: 1rem 2rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

nav {
  display: flex;
  gap: 1.5rem;
}

a {
  color: white;
  text-decoration: none;
  font-weight: bold;
}

a.router-link-active {
  color: #38bdf8;
}
</style>
